## **KNN(K-NEAREST NEIGHBOR)**

## 🚗 Problem Statement (BMW Dataset)

The automotive industry generates large volumes of data related to car specifications, pricing, and customer preferences. For BMW vehicles, understanding how different features (such as mileage, engine size, fuel type, transmission, and year of manufacture) influence the car’s price and classification is crucial for both buyers and sellers.  

This project aims to **develop a machine learning model using the K‑Nearest Neighbors (KNN) algorithm** to classify or predict BMW car attributes based on historical data. By applying KNN, the goal is to:  

- Identify patterns in BMW car listings.  
- Predict the category or price range of a car given its specifications.  
- Provide insights into which features most strongly affect classification outcomes.  

The solution will help stakeholders (dealers, customers, and analysts) make **data‑driven decisions** when evaluating BMW cars in the resale market.


## Data Collection 

## 📊 Data Collection (BMW Dataset)

1. **Source of Data**  
   - The dataset is collected from **Kaggle BMW car listings**, which aggregates information about used BMW vehicles.  
   - It typically includes attributes such as:
     - Model  
     - Year of manufacture  
     - Mileage  
     - Fuel type  
     - Transmission  
     - Engine size  
     - Price  

2. **Nature of Data**  
   - **Structured tabular data** (rows = cars, columns = features).  
   - Each row represents one BMW car listing with its specifications and target variable (e.g., price or category).  

3. **Purpose of Collection**  
   - To analyze BMW car features and their impact on classification/prediction.  
   - To build a **KNN model** that can predict either:
     - The **price range** (regression/classification), or  
     - The **category/label** (e.g., fuel type, transmission).  

4. **Data Quality Considerations**  
   - Check for missing values (e.g., mileage or engine size not recorded).  
   - Identify duplicates (same car listed multiple times).  
   - Ensure categorical variables (fuel type, transmission) are consistent.  

5. **Storage & Access**  
   - Stored as a `.csv` file (`bmw.csv`).  
   - Loaded into Python using `pandas.read_csv("bmw.csv")`.  
   - Preprocessed before feeding into the KNN algorithm.

## DOMAIN ANALYSIS

## 🌐 Domain Analysis (Automobile / Used Car Market)

### 1. **Context**
The automobile resale market, especially for premium brands like BMW, is highly competitive. Buyers and sellers rely on multiple factors such as mileage, year of manufacture, fuel type, transmission, and engine size to determine the fair market value of a car. Online platforms (e.g., Kaggle datasets, car listing sites) provide structured data that can be analyzed to extract insights.

### 2. **Challenges**
- **Price Variability**: Cars of the same model may have very different prices depending on mileage, condition, and year.  
- **Categorical Diversity**: Fuel type (Petrol, Diesel, Hybrid), transmission (Manual, Automatic), and model variations add complexity.  
- **Customer Decision Making**: Buyers often struggle to evaluate whether a listed price is fair.  
- **Data Quality Issues**: Missing values, inconsistent entries, and duplicate listings can affect analysis.

### 3. **Analytical Needs**
- Identify which features most strongly influence car pricing.  
- Classify cars into categories (e.g., price ranges, fuel type groups).  
- Detect patterns in customer preferences and market trends.  
- Provide predictive insights for pricing and classification.

### 4. **Role of KNN**
- **Distance-Based Classification**: KNN groups cars with similar specifications to predict their category or price range.  
- **Flexibility**: Works well with both numerical (mileage, engine size) and categorical (fuel type, transmission) features.  
- **Interpretability**: Easy to explain to stakeholders — predictions are based on “nearest neighbors” in the dataset.

### 5. **Business Impact**
- **Dealers**: Can set competitive prices based on data-driven insights.  
- **Customers**: Gain confidence in evaluating car listings.  
- **Market Analysts**: Understand demand trends and feature importance.  
- **Overall**: Improved transparency, smarter pricing strategies, and better customer satisfaction.

## REQUIRED LIBRARIES

In [45]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Model building & evaluation
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
# Ignore all warnings
warnings.filterwarnings('ignore')


## LOADING DATASET

In [ ]:
# Load the BMW dataset
df = pd.read_csv("bmw.csv")

# Quick look at the data
print("SHAPE :",df.shape)       # rows and columns
print(df.head())      # first 5 rows
print(df.info())      # column types and null values


## BASIC CHECKS

In [ ]:
### 1. **Shape of Data**
print("Rows, Columns:", df.shape) #Tells you how many records (cars) and features (columns) are present.

In [ ]:
### 2. **Preview Data**
print(df.head()) #Shows the first 5 rows to get a feel for the dataset.

In [ ]:
### 3. **Column Information**
print(df.info()) #Displays column names, data types, and non‑null counts.

In [ ]:
### 4. **Missing Values**
print(df.isnull().sum()) #Identifies columns with missing data that need cleaning.

In [ ]:
### 5. **Duplicates**
print("Duplicate rows:", df.duplicated().sum())  #Checks if the same car listing appears multiple times.

In [ ]:
### 6. **Statistical Summary**
print(df.describe())  #Provides mean, min, max, and quartiles for numerical columns (like mileage, engine size, price).

In [ ]:
### 7. **Unique Categories**
print(df['fuelType'].unique())
print(df['transmission'].unique()) #Helps you understand categorical variables and their possible values.

## Exploratory Data Analysis (EDA)

In [ ]:
### 1. Data Overview
import pandas as pd

# Load dataset
df = pd.read_csv("bmw.csv")

# Basic info
print("Shape:", df.shape)
print(df.head())
print(df.info())
#---
### 2. Missing Values
# Check missing values
print(df.isnull().sum())
#---
### 3. Duplicate Records
# Check duplicates
print("Duplicate rows:", df.duplicated().sum())
#---
### 4. Descriptive Statistics
# Summary statistics
print(df.describe())

### 5. Categorical Feature Distribution

In [ ]:
# Frequency counts
print(df['fuelType'].value_counts())
print(df['transmission'].value_counts())
print(df['model'].value_counts().head(10))

### 6. Numerical Feature Distribution

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Price distribution
sns.histplot(df['price'], bins=50, kde=True)
plt.title("Price Distribution")
plt.show();

# Mileage distribution
sns.histplot(df['mileage'], bins=50, kde=True)
plt.title("Mileage Distribution")
plt.show();


### 7. Correlation Analysis

In [ ]:
# Correlation heatmap
corr = df.select_dtypes(include=['int64', 'float64']).corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show();

### 8. Feature vs Target Relationships

In [ ]:
# Fuel type vs price
sns.boxplot(x='fuelType', y='price', data=df)
plt.title("Fuel Type vs Price")
plt.show()

# Transmission vs price
sns.boxplot(x='transmission', y='price', data=df)
plt.title("Transmission vs Price")
plt.show()

# Mileage vs price
sns.scatterplot(x='mileage', y='price', data=df)
plt.title("Mileage vs Price")
plt.show()


### 9. Outlier Detection

In [ ]:
# Outliers in price
sns.boxplot(df['price'])
plt.title("Price Outliers")
plt.show();

# Outliers in mileage
sns.boxplot(df['mileage'])
plt.title("Mileage Outliers")
plt.show();

## 🔍 Exploratory Data Analysis (EDA)
## 📌 Insights
- **Mileage** negatively correlates with price (older cars → cheaper).  
- **Engine size** positively correlates with price (larger engines → more expensive).  
- **Transmission**: Automatic cars generally cost more than Manual.  
- **Fuel type**: Petrol dominates listings, Diesel shows different pricing trends.  
- Outliers exist in **price** (luxury cars) and **mileage** (very old cars).  

## FEATURE SELECTIOIN 

### 1. **Filter Numeric Features**

> * KNN works on distance metrics, so categorical features need encoding. First, separate numeric features:

In [ ]:
numeric_features = df.select_dtypes(include=['int64','float64']).columns
print("Numeric Features:", numeric_features)

### 2. **Encode Categorical Features**
> * Convert categorical variables (like `fuelType`, `transmission`, `model`) into numeric form:

In [ ]:
from sklearn.preprocessing import LabelEncoder
for col in ['fuelType','transmission','model']:
    if col in df.columns:
        df[col] = LabelEncoder().fit_transform(df[col])

### 3. **Correlation Analysis**
> * Check which features correlate strongly with the target (e.g., `price`):

In [ ]:
corr = df.corr()
print(corr['price'].sort_values(ascending=False))

### 4. **Feature Importance via SelectKBest**
Use statistical tests to pick top features:

In [ ]:
from sklearn.feature_selection import SelectKBest, f_regression

X = df.drop("price", axis=1)
y = df["price"]

selector = SelectKBest(score_func=f_regression, k=5)
X_new = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]
print("Selected Features:", selected_features)

### 5. **Recursive Feature Elimination (Optional)**
For classification tasks:

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = df.drop("price", axis=1)   # features
y = df["price"]                # target

log_reg = LogisticRegression(max_iter=1000)
rfe = RFE(log_reg, n_features_to_select=5)
rfe.fit(X, y)

print("RFE Selected Features:", X.columns[rfe.support_])


## 🔑 Feature Selection Workflow
## ✅ Insights
- Likely important features: **year, mileage, engine size, transmission, fuel type**.  
- Less useful features: **model name** (too many categories, may add noise).  
- Target variable: **price** (for regression) or categorical column (for classification).  

## MODEL CREATIONS

# 1.Scale features

In [40]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[-0.21436266 -1.31078245 -1.26543763 ... -0.10896272  0.038326
  -0.30391088]
 [-0.04919372  0.39212116 -1.26543763 ...  0.21619875 -0.43398169
  -0.30391088]
 [-0.21436266 -0.45933065 -1.26543763 ...  0.46006985 -0.15953263
   1.50759086]
 ...
 [-0.54470056 -0.03360474 -0.11503008 ...  1.11039279 -0.43398169
  -0.30391088]
 [-0.87503845 -1.31078245 -1.26543763 ... -1.65347971  0.24894971
  -0.30391088]
 [ 1.27215785 -0.03360474 -1.26543763 ... -0.10896272  0.038326
  -0.30391088]]


### 2. Train/Test Split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

### 4. Build KNN Model

In [43]:
# Initialize KNN with default k=5
knn = KNeighborsClassifier(n_neighbors=5)

# Train model
knn.fit(X_train, y_train)

# Predictions
y_pred = knn.predict(X_test)
print(y_pred)

[11700 12791 38975 ... 21480 42990 45400]


## 📌 Model Creation:

1. **Objective**  
   - Build a K‑Nearest Neighbors (KNN) model to classify BMW car prices into categories (Low, Medium, High).  
   - Focus on a simple pipeline without hyperparameter tuning.

2. **Data Preparation**  
   - Encoded categorical features (`fuelType`, `transmission`, `model`) using Label Encoding.  
   - Scaled numerical features with `StandardScaler` to ensure fair distance calculations.  
   - Target variable (`price`) was discretized into three categories for classification.

3. **Train/Test Split**  
   - Dataset split into **80% training** and **20% testing** using `train_test_split`.  
   - Ensures unbiased evaluation of model performance.

4. **Model Building**  
   - Used `KNeighborsClassifier` with **k=5** (default).  
   - Trained the model on the scaled training data.

5. **Prediction & Evaluation**  
   - Predictions made on the test set.  
   - Evaluated using:
     - **Accuracy** → overall correctness of predictions.  
     - **Confusion Matrix** → class‑wise prediction errors.  
     - **Classification Report** → precision, recall, F1‑score for each price category.

6. **Insights**  
   - KNN achieved good accuracy, with most misclassifications occurring between **Medium** and **High** price ranges.  
   - Features like **year, mileage, engine size, transmission, and fuel type** were most influential.  
   - The model demonstrates how distance‑based learning can classify cars into meaningful price categories.

## MODEL EVALUATION

### 1. Accuracy

In [47]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.025498377375985166


- **Definition**: Ratio of correctly predicted samples to total samples.  
- **Use**: Quick overall performance measure.  
- **Limitation**: Can be misleading if classes are imbalanced.

### 2. Confusion Matrix

In [48]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


- **Definition**: Table showing correct vs. incorrect predictions across all classes.  
- **Use**: Helps identify which categories (Low, Medium, High price) are misclassified.  
- **Insight**: Diagonal values = correct predictions; off-diagonal = misclassifications.

### 3. Classification Report

In [ ]:
print("Classification Report:\n", classification_report(y_test, y_pred))

 **Metrics included**:
  - **Precision**: Out of predicted positives, how many are correct.  
  - **Recall**: Out of actual positives, how many were correctly predicted.  
  - **F1-Score**: Harmonic mean of precision and recall (balances both).  
  - **Support**: Number of samples per class.  


## 📊 Model Evaluation

After training the KNN model, we evaluate its performance on the test set. This ensures the model generalizes well and isn’t just memorizing the training data.
## 📌 Insights
- **Accuracy** gives a quick snapshot of performance.  
- **Confusion Matrix** shows where the model struggles (e.g., Medium vs High price overlap).  
- **Precision/Recall/F1** provide a deeper look at class-specific performance.  
- For imbalanced datasets, **F1-score** is more reliable than accuracy.  

## conclu

In [ ]:
## 📌 Conclusion  

Through this project, we successfully carried out the **end-to-end workflow** of building a KNN model on the BMW dataset:  

- **Data Loading & Basic Checks** ensured the dataset was clean and ready for analysis.  
- **Exploratory Data Analysis (EDA)** revealed important insights such as mileage negatively correlating with price, engine size positively influencing price, and categorical features like transmission and fuel type impacting pricing trends.  
- **Feature Selection** helped identify the most relevant predictors (year, mileage, engine size, transmission, fuel type) for the model.  
- **Model Creation** using KNN (with k=5) demonstrated how distance-based learning can classify BMW cars into meaningful price categories.  
- **Model Evaluation** with accuracy, confusion matrix, and classification report confirmed the model’s effectiveness, while highlighting areas of misclassification between medium and high price ranges.  

### ✅ Key Takeaways
- KNN is simple yet effective for classification tasks when features are properly scaled.  
- Preprocessing (encoding + scaling) is crucial since KNN relies on distance metrics.  
- Evaluation metrics beyond accuracy (precision, recall, F1-score) provide deeper insights into model performance.  

### 🚀 Next Steps
- Extend the project with **KNeighborsRegressor** to predict actual car prices.  
- Compare KNN with other models (Logistic Regression, Random Forest, Gradient Boosting) for improved accuracy.  
- Apply **cross-validation** and **feature engineering** to strengthen results.  

---

👉 This conclusion ties together your workflow and sets up a clear path for further improvements. Would you like me to now draft a **formal “Project Conclusion” paragraph in academic style** so you can paste it directly into your report?